<?php

namespace Database\Seeders;

use App\Models\Layanan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                'id' => '1',
                'kategori_layanan_id' => '1',
                'name' => 'Perpanjangan Studi',
                'url_mhs' => 'http://127.0.0.1:8000/perpanjanganStudi',
                'url_staff' => 'http://127.0.0.1:8000/perpanjanganStudi',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '1',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Catatan :</p><ul class="text-dark"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '2',
                'kategori_layanan_id' => '1',
                'name' => 'Penundaan Pembayaran UKT',
                'url_mhs' => 'http://127.0.0.1:8000/penundaan',
                'url_staff' => 'http://127.0.0.1:8000/penundaan',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '2',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Catatan :</p><ul class="text-dark"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Bagi Mahasiswa D3 semester 7 keatas dan Mahasiswa D4 semester 8 keatas <span style="font-weight: bolder;">Wajib mengajukan <a href="http://127.0.0.1:8000/perpanjanganStudi">Perpanjangan Studi</a></span> sebelum mengajukan Penundaan Pembayaran UKT.</li><li>Mahasiswa wajib mengecek status ajuan dan status penundaan di menu siakad.uns.ac.id sampai disetujui oleh Universitas</li><li>Mahasiswa tidak perlu mengurus ke Akademik Pusat</li></ul>',
            ],
            [
                'id' => '3',
                'kategori_layanan_id' => '1',
                'name' => 'Selang/Cuti',
                'url_mhs' => 'http://127.0.0.1:8000/selang',
                'url_staff' => 'http://127.0.0.1:8000/selang',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '3',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Catatan :</p><ul class="text-dark"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Mahasiswa mengajukan Selang / Cuti terlebih dahulu di Siakad</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '4',
                'kategori_layanan_id' => '1',
                'name' => 'Undur Diri',
                'url_mhs' => 'http://127.0.0.1:8000/undurDiri',
                'url_staff' => 'http://127.0.0.1:8000/undurDiri',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '4',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Catatan :</p><ul class="text-dark"><li>Sebelum mengajukan ajuan, mahasiswa Wajib mengajukan Undur Diri di SIAKAD terlebih dahulu</li><li>Mahasiswa WAJIB melunasi segala bentuk tagihan yang tertera di Siakad</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '5',
                'kategori_layanan_id' => '1',
                'name' => 'Pembayaran UKT di Luar Jadwal',
                'url_mhs' => 'http://127.0.0.1:8000/diluarJadwal',
                'url_staff' => 'http://127.0.0.1:8000/diluarJadwal',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '5',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Catatan :</p><ul class="text-dark"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '6',
                'kategori_layanan_id' => '1',
                'name' => 'Keringanan UKT',
                'url_mhs' => 'http://127.0.0.1:8000/ukt/informasi',
                'url_staff' => 'http://127.0.0.1:8000/ukt',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '6',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => null,
            ],
            [
                'id' => '7',
                'kategori_layanan_id' => '1',
                'name' => 'Layanan Surat Keterangan Lulus',
                'url_mhs' => 'http://127.0.0.1:8000/skl',
                'url_staff' => 'http://127.0.0.1:8000/skl',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '7',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => null,
            ],
            [
                'id' => '8',
                'kategori_layanan_id' => '1',
                'name' => 'Verifikasi Wisuda',
                'url_mhs' => 'http://127.0.0.1:8000/verifikasiWisuda',
                'url_staff' => 'http://127.0.0.1:8000/verifikasiWisuda',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '8',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<span>Ajukan Verifikasi wisuda jika sudah mendapat SKL. Verifikasi wisuda akan dilakukan jika sudah mendapatkan No Seri Ijazah Nasional.</span>',
            ],
            [
                'id' => '9',
                'kategori_layanan_id' => '1',
                'name' => 'Transkrip Nilai',
                'url_mhs' => 'http://127.0.0.1:8000/transkrip',
                'url_staff' => 'http://127.0.0.1:8000/transkrip',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '9',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => null,
            ],
            [
                'id' => '10',
                'kategori_layanan_id' => '1',
                'name' => 'SKPI',
                'url_mhs' => 'http://127.0.0.1:8000/skpi',
                'url_staff' => 'http://127.0.0.1:8000/skpi',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '10',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => null,
            ],
            [
                'id' => '11',
                'kategori_layanan_id' => '1',
                'name' => 'Pengajuan TTD TA',
                'url_mhs' => 'http://127.0.0.1:8000/TA',
                'url_staff' => 'http://127.0.0.1:8000/TA',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '11',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<p class="text-dark">Layanan pengajuan tanda tangan lembar pengesahan tugas akhir untuk mahasiswa yang telah menyelesaikan tugas akhir.</p>',
            ],
            [
                'id' => '12',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Keterangan/Pengantar',
                'url_mhs' => 'http://127.0.0.1:8000/suket',
                'url_staff' => 'http://127.0.0.1:8000/suket',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '1',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => 'SuratKeteranganPengantar.docx',
                'keterangan' => '<p class="text-dark">Surat Keterangan / Pengantar adalah surat yang menerangkan bahwa Anda berstatus aktif sebagai mahasiswa dan digunakan untuk keperluan <span class="text-danger" style="font-weight: bolder;">bersifat Umum</span>, diantaranya adalah untuk keperluan:</p><ul><li class="text-dark">pengantar ke kantor kepolisian untuk mengurus kehilangan</li><li class="text-dark">syarat pembukaan rekening bank</li><li class="text-dark">syarat pendaftaran suatu lomba/kegiatan</li><li class="text-dark">syarat pendaftaran beasiswa</li><li class="text-dark">syarat mengurus bpjs</li><li class="text-dark">syarat permohonan layanan kesehatan</li><li class="text-dark">dan lain-lain …..</li></ul>',
            ],
            [
                'id' => '13',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Keterangan Masih Kuliah',
                'url_mhs' => 'http://127.0.0.1:8000/skmk',
                'url_staff' => 'http://127.0.0.1:8000/skmk',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '2',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => 'SuratKeteranganMasihKuliah.docx',
                'keterangan' => '<span>Surat Keterangan Masih Kuliah adalah surat yang dipergunakan sebagai lampiran <span class="text-danger" style="font-weight: bolder;">pengusulan Tunjangan Anak (PNS, TNI/Polri)</span> dengan ketentuan belum menikah, benar-benar menjadi tanggungan orangtua/wali dan tidak terikat beasiswa ikatan dinas.</span><br><span>Apabila dikemudian hari Anda mengisikan data yang tidak benar yang mengakibatkan kerugian Negara Republik Indonesia maka Anda bersedia untuk menanggung kerugian tersebut.</span>',
            ],
            [
                'id' => '14',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Tugas Delegasi',
                'url_mhs' => 'http://127.0.0.1:8000/st',
                'url_staff' => 'http://127.0.0.1:8000/st',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '3',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => 'SuratTugasDelegasi.docx',
                'keterangan' => '<p class="text-dark">Tahapan Permohonan Surat Tugas Delegasi (Kegiatan Lomba)</p><ol class="text-dark"><li>Klik tombol Tambah Ajuan</li><li>Mengisi Form Permohonan</li><li>Menggunggah berkas persyaratan sebagai berikut:<ol class="text-dark"><li>Jika mengajukan dana ke Sekolah Vokasi<ul class="text-dark"><li>Surat Pengantar "Permohonan Delegasi" dari Program Studi</li><li>Surat "Permohonan Dana"</li><li>Lembar "Pernyataan LPJ dan SPJ"</li><li>ToR RAB Lomba</li><li>Pamflet/Undangan Lomba</li></ul></li><li>Jika tidak mengajukan dana ke Sekolah Vokasi<ul class="text-dark"><li>Surat Pengantar " Permohonan Delegasi" dari Program Studi</li><li>Lembar "Pernyataan LPJ"</li><li>Pamflet/Undangan Lomba</li></ul></li></ol></li></ol>',
            ],
            [
                'id' => '15',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Izin Kegiatan',
                'url_mhs' => 'http://127.0.0.1:8000/sik',
                'url_staff' => 'http://127.0.0.1:8000/sik',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '4',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => 'SuratIzinKegiatan.docx',
                'keterangan' => '<p class="text-dark">Saat Anda mengajukan Surat Izin Kegiatan, Anda wajib mengunggah Proposal Kegiatan dan Lampiran.<br>Untuk Lampiran terdiri dari:</p><ul class="text-dark"><li>Surat "Permohonan Izin Kegiatan"</li><li>Form "Analisa Resiko Kegiatan"</li><li>Lembar "Pengesahan Kegiatan"</li><li>Lembar "Pengesahan Dana" (jika menggunakan dana)</li><li>Lembar "Pemohonan Dana" (jika menggunakan dana)</li><li>Lembar Penyataan tentang "LPJ dan SPJ" Kegiatan</li></ul><p class="text-dark">Mohon diperhatikan:</p><ol class="text-dark"><li>Proposal dan Laporan Pertanggungjawaban Kegiatan (LPJ) dibuat dengan ukuran kertas kuarto dan di sisi kanan atas disediakan kolom Nomor dan Tahun.</li><li>LPJ dan SPJ diserahkan sesuai dengan tanggal yang ada di Lembar Pernyataan.</li><li>Format lampiran sudah disediakan silahkan diisi dan tidak dirubah bentuknya.</li><li>Lampiran Surat Permohonan Izin Kegiatan menggunakan KOP Resmi Ormawa</li><li>Permohonan Izin Kegiatan diajukan maksimal satu minggu sebelum kegiatan dilaksanakan.</li></ol>',
            ],
            [
                'id' => '16',
                'kategori_layanan_id' => '2',
                'name' => 'Laporan Pertanggungjawaban',
                'url_mhs' => 'http://127.0.0.1:8000/lpj',
                'url_staff' => 'http://127.0.0.1:8000/lpj',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '5',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '<span>Setiap Ajuan Surat Tugas Delegasi dan Surat Izin Kegiatan yang telah selesai, Mahasiswa atau Ormawa wajib mengupload Laporan Pertanggungjawaban</span>',
            ],
            [
                'id' => '17',
                'kategori_layanan_id' => '3',
                'name' => 'Legalisir',
                'url_mhs' => 'http://127.0.0.1:8000/legalisir/informasi',
                'url_staff' => 'http://127.0.0.1:8000/legalisir',
                'is_active' => '1',
                'is_default' => '1',
                'urutan' => '1',
                'semester_id' => null,
                'tahun_akademik_id' => null,
                'open_datetime' => null,
                'close_datetime' => null,
                'template_surat_hasil' => null,
                'keterangan' => '',
            ],
        ];

        foreach ($data as $item) {
            Layanan::create($item);
        }
    }
}
