<?php

namespace Database\Seeders;

use App\Models\Layanan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => '1',
                'kategori_layanan_id' => '1',
                'name' => 'Perpanjangan Studi',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/perpanjanganStudi',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/perpanjanganStudi',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '1',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Catatan :</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '2',
                'kategori_layanan_id' => '1',
                'name' => 'Penundaan Pembayaran UKT',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/penundaan',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/penundaan',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor"]),
                'urutan' => '2',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Catatan :</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Bagi Mahasiswa D3 semester 7 keatas dan Mahasiswa D4 semester 8 keatas&nbsp;<span style="font-weight: bolder;">Wajib mengajukan&nbsp;<a href="https://layananbaru.vokasi.uns.ac.id/perpanjanganStudi" style="color: rgb(58, 87, 232); text-decoration: none;">Perpanjangan Studi</a></span>&nbsp;sebelum mengajukan Penundaan Pembayaran UKT.</li><li>Mahasiswa wajib mengecek status ajuan dan status penundaan di menu siakad.uns.ac.id sampai disetujui oleh Universitas</li><li>Mahasiswa tidak perlu mengurus ke Akademik Pusat</li></ul>',
            ],
            [
                'id' => '3',
                'kategori_layanan_id' => '1',
                'name' => 'Selang/Cuti',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/selang',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/selang',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '3',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Catatan :</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Mahasiswa mengajukan Selang / Cuti terlebih dahulu di Siakad</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '4',
                'kategori_layanan_id' => '1',
                'name' => 'Undur Diri',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/undurDiri',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/undurDiri',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '4',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Catatan :</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Sebelum mengajukan ajuan, mahasiswa Wajib mengajukan Undur Diri di SIAKAD terlebih dahulu</li><li>Mahasiswa WAJIB melunasi segala bentuk tagihan yang tertera di Siakad</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '5',
                'kategori_layanan_id' => '1',
                'name' => 'Pembayaran UKT di Luar Jadwal',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/diluarJadwal',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/diluarJadwal',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '5',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Catatan :</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Pengajuan diluar jadwal ajuan harus mendatangi Akademik Sekolah Vokasi</li><li>Surat Pengantar yang sudah ditanda tangani Wakil Dekan Akademik, Riset dan Kemahasiswaan Sekolah Vokasi WAJIB diambil di Front Office Sekolah Vokasi</li><li>Surat Pengantar yang sudah diambil, WAJIB diserahkan ke Akademik UNS (Pusat) oleh mahasiswa</li></ul>',
            ],
            [
                'id' => '6',
                'kategori_layanan_id' => '1',
                'name' => 'Keringanan UKT',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/ukt/informasi',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/ukt',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["staff"]),
                'urutan' => '6',
                'keterangan' => null,
            ],
            [
                'id' => '7',
                'kategori_layanan_id' => '1',
                'name' => 'Layanan Surat Keterangan Lulus',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/skl',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/skl',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '7',
                'keterangan' => null,
            ],
            [
                'id' => '8',
                'kategori_layanan_id' => '1',
                'name' => 'Verifikasi Wisuda',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/verifikasiWisuda',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/verifikasiWisuda',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor"]),
                'urutan' => '8',
                'keterangan' => '<span style="color: rgb(35, 45, 66); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Ajukan Verifikasi wisuda jika sudah mendapat SKL. Verifikasi wisuda akan dilakukan jika sudah mendapatkan No Seri Ijazah Nasional.</span>',
            ],
            [
                'id' => '9',
                'kategori_layanan_id' => '1',
                'name' => 'Transkrip Nilai',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/transkrip',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/transkrip',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '9',
                'keterangan' => null,
            ],
            [
                'id' => '10',
                'kategori_layanan_id' => '1',
                'name' => 'SKPI',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/skpi',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/skpi',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor","fo"]),
                'urutan' => '10',
                'keterangan' => null,
            ],
            [
                'id' => '11',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Keterangan/Pengantar',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/suket',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/suket',
                'template_surat_hasil' => 'suket.docx',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor"]),
                'urutan' => '1',
                'template_surat_hasil' => 'SuratKeteranganPengantar.docx',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Surat Keterangan / Pengantar adalah surat yang menerangkan bahwa Anda berstatus aktif sebagai mahasiswa dan digunakan untuk keperluan&nbsp;<span class="text-danger" style="font-weight: bolder; --bs-text-opacity: 1;">bersifat Umum</span>, diantaranya adalah untuk keperluan:</p><ul style="color: rgb(138, 146, 166); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li class="text-dark" style="--bs-text-opacity: 1;">pengantar ke kantor kepolisian untuk mengurus kehilangan</li><li class="text-dark" style="--bs-text-opacity: 1;">syarat pembukaan rekening bank</li><li class="text-dark" style="--bs-text-opacity: 1;">syarat pendaftaran suatu lomba/kegiatan</li><li class="text-dark" style="--bs-text-opacity: 1;">syarat pendaftaran beasiswa</li><li class="text-dark" style="--bs-text-opacity: 1;">syarat mengurus bpjs</li><li class="text-dark" style="--bs-text-opacity: 1;">syarat permohonan layanan kesehatan</li><li class="text-dark" style="--bs-text-opacity: 1;">dan lain-lain …..</li></ul>',
            ],
            [
                'id' => '12',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Keterangan Masih Kuliah',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/skmk',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/skmk',
                'template_surat_hasil' => 'skmk.docx',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor"]),
                'urutan' => '2',
                'template_surat_hasil' => 'SuratKeteranganMasihKuliah.docx',
                'keterangan' => '<span style="color: rgb(33, 37, 41); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Surat Keterangan Masih Kuliah adalah surat yang dipergunakan sebagai lampiran&nbsp;</span><span class="text-danger" style="font-weight: bolder; --bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">pengusulan Tunjangan Anak (PNS, TNI/Polri)</span><span style="color: rgb(33, 37, 41); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">&nbsp;dengan ketentuan belum menikah, benar-benar menjadi tanggungan orangtua/wali dan tidak terikat beasiswa ikatan dinas.</span><br style="color: rgb(33, 37, 41); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><span style="color: rgb(33, 37, 41); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Apabila dikemudian hari Anda mengisikan data yang tidak benar yang mengakibatkan kerugian Negara Republik Indonesia maka Anda bersedia untuk menanggung kerugian tersebut.</span>',
            ],
            [
                'id' => '13',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Tugas Delegasi',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/st',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/st',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","staff","dekanat","subkoor"]),
                'urutan' => '3',
                'template_surat_hasil' => 'SuratTugasDelegasi.docx',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Tahapan Permohonan Surat Tugas Delegasi (Kegiatan Lomba)</p><ol class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Klik tombol Tambah Ajuan</li><li>Mengisi Form Permohonan</li><li>Menggunggah berkas persyaratan sebagai berikut:<ol class="text-dark" style="--bs-text-opacity: 1;"><li>Jika mengajukan dana ke Sekolah Vokasi<ul class="text-dark" style="--bs-text-opacity: 1;"><li>Surat Pengantar “Permohonan Delegasi” dari Program Studi</li><li>Surat “Permohonan Dana”</li><li>Lembar “Pernyataan LPJ dan SPJ”</li><li>ToR RAB Lomba</li><li>Pamflet/Undangan Lomba</li></ul></li><li>Jika tidak mengajukan dana ke Sekolah Vokasi<ul class="text-dark" style="--bs-text-opacity: 1;"><li>Surat Pengantar “ Permohonan Delegasi” dari Program Studi</li><li>Lembar “Pernyataan LPJ”</li><li>Pamflet/Undangan Lomba</li></ul></li></ol></li></ol>',
            ],
            [
                'id' => '14',
                'kategori_layanan_id' => '2',
                'name' => 'Surat Izin Kegiatan',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/sik',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/sik',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["ormawa","staff","dekanat","subkoor"]),
                'urutan' => '4',
                'template_surat_hasil' => 'SuratIzinKegiatan.docx',
                'keterangan' => '<p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Saat Anda mengajukan Surat Izin Kegiatan, Anda wajib mengunggah Proposal Kegiatan dan Lampiran.<br>Untuk Lampiran terdiri dari:</p><ul class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Surat “Permohonan Izin Kegiatan”</li><li>Form “Analisa Resiko Kegiatan”</li><li>Lembar “Pengesahan Kegiatan”</li><li>Lembar “Pengesahan Dana” (jika menggunakan dana)</li><li>Lembar “Pemohonan Dana” (jika menggunakan dana)</li><li>Lembar Penyataan tentang “LPJ dan SPJ” Kegiatan</li></ul><p style="color: rgb(138, 146, 166); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"></p><p class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Mohon diperhatikan:</p><ol class="text-dark" style="--bs-text-opacity: 1; font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;"><li>Proposal dan Laporan Pertanggungjawaban Kegiatan (LPJ) dibuat dengan ukuran kertas kuarto dan di sisi kanan atas disediakan kolom Nomor dan Tahun.</li><li>LPJ dan SPJ diserahkan sesuai dengan tanggal yang ada di Lembar Pernyataan.</li><li>Format lampiran sudah disediakan silahkan diisi dan tidak dirubah bentuknya.</li><li>Lampiran Surat Permohonan Izin Kegiatan menggunakan KOP Resmi Ormawa</li><li>Permohonan Izin Kegiatan diajukan maksimal satu minggu sebelum kegiatan dilaksanakan.</li></ol>',
            ],
            [
                'id' => '15',
                'kategori_layanan_id' => '2',
                'name' => 'Laporan Pertanggungjawaban',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/lpj',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/lpj',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["mahasiswa","ormawa","staff","dekanat","subkoor"]),
                'urutan' => '5',
                'keterangan' => '<span style="color: rgb(33, 37, 41); font-family: Inter, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Setiap Ajuan Surat Tugas Delegasi dan Surat Izin Kegiatan yang telah selesai, Mahasiswa atau Ormawa wajib mengupload Laporan Pertanggungjawaban</span>',
            ],
            [
                'id' => '16',
                'kategori_layanan_id' => '3',
                'name' => 'Legalisir',
                'url_mhs' => 'https://layananbaru.vokasi.uns.ac.id/legalisir/informasi',
                'url_staff' => 'https://layananbaru.vokasi.uns.ac.id/legalisir',
                'is_active' => '1',
                'is_default' => '1',
                // 'gate' => json_encode(["staff","dekanat","subkoor","fo"]),
                'urutan' => '1',
                'keterangan' => '',
            ],
        ];

        foreach ($data as $i) {
            Layanan::create($i);
        }
    }
}
